### ISSUE TITLE
wwwroot folder is not generated

### ISSUE THREAD

**Issue by kstr** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#1]
wwwroot folder is not generated.  The project cannot be started in debug without manually creating the folder.

**Comment by WillemDN** [comment]
Running the default task from the gulp file will generate te wwwroot folder and add all predefined files to it.

**Comment by kstr** [comment]
In the API-only version of the generator, the gulp file is just a stub by default.  Should the creation of an empty wwwroot folder (and .gitkeep file) be handled there?  In any case, a newly generated solution does not fire up without the folder so i believe it should either be generated along with the rest or put in the gulpfile.

**Comment by StevenVandenBroeck** [comment]
Fixed in version 1.0.2. 
You can do an 'npm install -g generator-dgp-api-aspnetcore' to get the latest version.
