### ISSUE TITLE
Logging werkt niet (in docker) (ACC)

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#18]

**Comment by erikseynaeve** [comment]
@Stephan-Ghequiere 
Is dit issue nog relevant?  Anders kan dit afgesloten worden.

In tussentijd zijn er al een aantal code-aanpassingen gebeurd en zou logging gewoon moeten werken. Als logging in DEV werkte en niet in ACC, lag dit vaak ook eerder aan configuratie dan aan de code van de Starterkit.
