### ISSUE TITLE
IntegrationTests: gegenereerde code werkt niet

### ISSUE THREAD

**Issue by QuintenGeoSolutions** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#25]
Bij het genereren van een nieuw project is het niet mogelijk om de integratietests die wordt aangemaakt te laten werken. Er wordt geen configuratie ingeladen en dit geeft problemen.

Ideaal zou er een apparte configuratie kunnen worden meegegeven.

**Comment by Jonah-Jordan** [comment]
Probleem lijkt met laatste wijzigingen opgelost.

**Comment by erikseynaeve** [comment]
wordt afgesloten op aanwijzing van Jonah-Jordan
