### ISSUE TITLE
yeoman generator updaten

### ISSUE THREAD

**Issue by Jonah-Jordan** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#30]
Momenteel genereert de globaal te installeren yeoman nog steeds een 2.2 project, dit moet nog gepublished worden

**Comment by Jonah-Jordan** [comment]
Blijkbaar toch inorde :)

**Comment by Jonah-Jordan** [comment]
Yeoman genereert nog steeds 2.2

**Comment by erikseynaeve** [comment]
Jonah, de laatste versie van de code is gepubliceerd naar npm.js als versie 8.0.4. Dit zou een netcoreapp3.1 moeten genereren.

https://www.npmjs.com/package/generator-dgp-api-aspnetcore

Ter info: er wordt momenteel nog verder gewerkt aan deze starterkit (en andere toolboxen) om de manier en output van logging aan te passen en de dataAccess-laag mee in de toolbox zelf te steken. Er gaan dus normaal op korte termijn nog versies volgen.
