### ISSUE TITLE
Docker niet aangepast naar .net sdk 5

### ISSUE THREAD

**Issue by Jonah-Jordan** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#36]
Docker build faalt omdat de juiste .Net SDK niet opgehaald wordt. Staat momenteel nog op 3.1.
Ik heb dit in PR #35 aangepast en getest.

**Comment by erikseynaeve** [comment]
Pull request is gemerged.  Voor een update van npm-package zal nog even gewacht worden op pull request #28 . Als dit sneller nodig is, kan dit door gebruik te maken van npm-link met lokale code.

**Comment by erikseynaeve** [comment]
@Jonah-Jordan 
De nodige pull requests waren afgehandeld. Er is daarom ook een nieuwe versie op npm gezet, v9.0.0

**Comment by Jonah-Jordan** [comment]
@erikseynaeve ok top bedankt!
