### ISSUE TITLE
Source is unreachable and outdated

### ISSUE THREAD

**Issue by RobLiekens** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#38]
Builds failing, please remove this source (check other .NET templates too)

https://github.com/digipolisantwerp/generator-dgp-api-aspnetcore_yeoman/blob/352f46bfd9679096fe5802662f9b1966900761c9/generators/app/templates/nuget.config#L5

**Comment by erikseynaeve** [comment]
The obsolete nuget package source has been removed from nuget.config
