### ISSUE TITLE
Unit test fails in new project 

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#47]
OutgoingRequestLoggerTest.ShouldLogOutgoingRequest fails.
Replace  
`Assert.Contains(logs, l => l.MessageTemplate.Text == "Outgoing API call response");`
with
` Assert.Contains(logs, l => l.MessageTemplate.Text.Contains("outgoing API call response"));`

**Comment by erikseynaeve** [comment]
Fix already included via https://github.com/digipolisantwerp/generator-dgp-api-aspnetcore_yeoman/pull/49
