### ISSUE TITLE
ObjectDisposedException in ExceptionHandler

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [digipolisantwerp/generator-dgp-api-aspnetcore_yeoman#48]
`an exception was thrown attempting to execute the error handler system.objectdisposedexception: cannot access a closed stream`
This exception is thrown when the exceptionhandler tries to write the errror object to the response stream. 
Reorder the middleware in Startup.Configure: 

` app.UseMiddleware<IncomingRequestLogger>();` should come before `app.UseApiExtensions();`

as the following code will close the stream (responsebody) when an exception is thrown without returning the original response stream:
        
             //Copy a pointer to the original response body stream
            var originalResponseBody = context.Response.Body;

            using (var responseBody = new MemoryStream())
            {
                context.Response.Body = responseBody;

                await _next(context);
                await LogRequest(context.Response, sw);
                responseBody.Seek(0, SeekOrigin.Begin);

                //Copy the contents of the new memory stream (which contains the response) to the original stream, which is then returned to the client
                await responseBody.CopyToAsync(originalResponseBody);
            }

**Comment by erikseynaeve** [comment]
Fix already included via https://github.com/digipolisantwerp/generator-dgp-api-aspnetcore_yeoman/pull/49
